---
name: CPAN-Mini-FromList
version: 0.01
author:
  - 'Thomas Klausner <domm@cpan.org>'
abstract: |-
  create a minimal mirror of CPAN containing
  only modules you specify
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  CPAN::Mini::FromList:
    file: lib/CPAN/Mini/FromList.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
